In [5]:
import pandas as pd

In [7]:
import warnings

In [9]:
warnings.filterwarnings('ignore')

In [13]:
df = pd.read_csv(r"C:\Users\HomePC\Downloads\archive (3)\Raw-Data.csv")

In [15]:
df.head()

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes
1,Italy,10-19,Female,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing","Pains,Nasal-Congestion,Runny-Nose",Moderate,No
2,Iran,20-24,Transgender,"Fever,Tiredness,Dry-Cough","Pains,Nasal-Congestion",Severe,Dont-Know
3,Republic of Korean,25-59,NaN,"Fever,Tiredness",Pains,NaN,NaN
4,France,60+,NaN,Fever,"Nasal-Congestion,Runny-Nose,Diarrhea",NaN,NaN

In [19]:
df.isnull().sum()

Country                   6
Age                      11
Gender                   13
Symptoms                  0
Experiencing_Symptoms     5
Severity                 13
Contact                  13
dtype: int64

In [21]:
df.Country.mode()

0                 China
1                France
2               Germany
3                  Iran
4                 Italy
5                 Other
6             Other-EUR
7    Republic of Korean
8                 Spain
9                   UAE
Name: Country, dtype: object

In [ ]:
import pandas as pd

# Load dataset
file_path = "/mnt/data/Raw-Data.csv"
df = pd.read_csv(file_path)

# Step 1: Handle Missing Values
# Fill missing categorical values with 'Unknown'
categorical_cols = ['Country', 'Age', 'Gender', 'Experiencing_Symptoms', 'Severity', 'Contact']
df[categorical_cols] = df[categorical_cols].fillna('Unknown')

# Step 2: Standardize Categories
# Replace 'Dont-Know' with 'Unknown' in the 'Contact' column
df['Contact'] = df['Contact'].replace('Dont-Know', 'Unknown')

# Step 3: Convert Age Ranges into Categories
def categorize_age(age):
    if age in ['0-9', '10-19']: return 'Child'
    elif age in ['20-24', '25-59']: return 'Adult'
    elif age == '60+': return 'Senior'
    else: return 'Unknown'

df['Age_Group'] = df['Age'].apply(categorize_age)

# Step 4: Remove duplicates
df = df.drop_duplicates()

# Step 5: Save cleaned data
cleaned_file_path = "/mnt/data/Cleaned-Data.csv"
df.to_csv(cleaned_file_path, index=False)

print("Data cleaning completed. Cleaned file saved at:", cleaned_file_path)

In [23]:
categorical_cols = ['Country', 'Age', 'Gender', 'Experiencing_Symptoms', 'Severity', 'Contact']
df[categorical_cols] = df[categorical_cols].fillna('Unknown')

In [ ]:
import pandas as pd

# Load the dataset
file_path = "/mnt/data/Raw-Data.csv"
df = pd.read_csv(file_path)

# Step 1: Check for missing values
print("Missing values before cleaning:\n", df.isnull().sum())

# Step 2: Replace missing values with the mode of each column
for column in df.columns:
    mode_value = df[column].mode()[0]  # Get the mode of the column
    df[column].fillna(mode_value, inplace=True)  # Replace NaN with mode

# Step 3: Verify that there are no missing values left
print("Missing values after cleaning:\n", df.isnull().sum())

# Save the cleaned data
cleaned_file_path = "/mnt/data/Cleaned-Data.csv"
df.to_csv(cleaned_file_path, index=False)

print("Data cleaning completed. Cleaned file saved as 'Cleaned-Data.csv'.")

In [25]:
for column in df.columns:
    mode_value = df[column].mode()[0]  # Get the mode of the column
    df[column].fillna(mode_value, inplace=True)  # Replace NaN with mode

In [27]:
df.isnull().sum()

Country                  0
Age                      0
Gender                   0
Symptoms                 0
Experiencing_Symptoms    0
Severity                 0
Contact                  0
dtype: int64

In [35]:
df.duplicated().sum()

0

In [37]:
df

,Country,Age,Gender,Symptoms,Experiencing_Symptoms,Severity,Contact
0,China,0-9,Male,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breath...","Pains,Nasal-Congestion,Runny-Nose,Diarrhea",Mild,Yes
1,Italy,10-19,Female,"Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing","Pains,Nasal-Congestion,Runny-Nose",Moderate,No
2,Iran,20-24,Transgender,"Fever,Tiredness,Dry-Cough","Pains,Nasal-Congestion",Severe,Dont-Know
3,Republic of Korean,25-59,Unknown,"Fever,Tiredness",Pains,Unknown,Unknown
4,France,60+,Unknown,Fever,"Nasal-Congestion,Runny-Nose,Diarrhea",Unknown,Unknown
5,Spain,Unknown,Unknown,"Tiredness,Dry-Cough,Difficulty-in-Breathing,So...","Nasal-Congestion,Runny-Nose",Unknown,Unknown
6,Germany,Unknown,Unknown,"Tiredness,Dry-Cough,Difficulty-in-Breathing",Nasal-Congestion,Unknown,Unknown
7,UAE,Unknown,Unknown,"Tiredness,Dry-Cough","Runny-Nose,Diarrhea",Unknown,Unknown
8,Other-EUR,Unknown,Unknown,Tiredness,Runny-Nose,Unknown,Unknown
9,Other,Unknown,Unknown,"Dry-Cough,Difficulty-in-Breathing,Sore-Throat",Diarrhea,Unknown,Unknown
10,Unknown,Unknown,Unknown,"Dry-Cough,Difficulty-in-Breathing",None_Experiencing,Unknown,Unknown
11,Unknown,Unknown,Unknown,Dry-Cough,Unknown,Unknown,Unknown
12,Unknown,Unknown,Unknown,"Difficulty-in-Breathing,Sore-Throat",Unknown,Unknown,Unknown
13,Unknown,Unknown,Unknown,Difficulty-in-Breathing,Unknown,Unknown,Unknown
14,Unknown,Unknown,Unknown,Sore-Throat,Unknown,Unknown,Unknown
15,Unknown,Unknown,Unknown,None_Sympton,Unknown,Unknown,Unknown

In [39]:
df1 = pd.read_csv(r"C:\Users\HomePC\Downloads\archive (3)\Cleaned-Data.csv")

In [41]:
df1

,Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,...,Gender_Male,Gender_Transgender,Severity_Mild,Severity_Moderate,Severity_None,Severity_Severe,Contact_Dont-Know,Contact_No,Contact_Yes,Country
0,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,0,1,China
1,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,0,1,0,China
2,1,1,1,1,1,0,1,1,1,1,...,1,0,1,0,0,0,1,0,0,China
3,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,0,1,China
4,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,0,0,1,0,China
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
316795,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,Other
316796,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,0,0,Other
316797,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,0,1,Other
316798,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,0,1,0,Other
316799,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,1,0,1,0,0,Other